apiVersion: apps/v1
kind: Deployment
metadata:
  name: testingcicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testingcicd
  template:
    metadata:
      labels:
        app: testingcicd
    spec:
      containers:
      - name: testingcicd
        image: karthiknk826/testingcicd:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

